name: Reusable Create S3 Bucket Workflow

on:
  workflow_call:
    inputs:
      S3_BUCKET_NAME:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      KMS_ARN:
        required: true  # Set to true if it's required by the script
        type: string
      LOG_LEVEL:
        required: false
        type: string
        default: "INFO"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  create-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3 pyyaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Run script to create S3 bucket
        run: |
          python connect/devops/core/scripts/createBootstrapS3Bucket.py \
            --s3BucketName "${{ inputs.S3_BUCKET_NAME }}" \
            --stackName "${{ inputs.STACK_NAME }}" \
            --AWSRegion "${{ inputs.AWS_REGION }}" \
            --KMSEncryptionKeyARN "${{ inputs.KMS_ARN }}" \
            --logLevel "${{ inputs.LOG_LEVEL }}"
