name: Trigger Delete S3 Bucket

on:
  workflow_dispatch:
    inputs:
      S3_BUCKET_NAME:
        description: "Name of the S3 bucket to delete"
        required: true
        type: string
      STACK_NAME:
        description: "CloudFormation stack name"
        required: true
        type: string
      AWS_REGION:
        description: "AWS Region"
        required: true
        type: string

jobs:
  trigger-delete:
    uses: ./.github/workflows/delete-s3-bucket.yml
    with:
      S3_BUCKET_NAME: ${{ inputs.S3_BUCKET_NAME }}
      STACK_NAME: ${{ inputs.STACK_NAME }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
