AWSTemplateFormatVersion: '2010-09-09'
Description: Apollo KMS Key
Parameters:
  UserArn:
    Type: String
  SSMKMSKeySSEArnName:
    Type: String
  SSMKMSKeyDataArnName:
    Type: String

Resources: 
  ApolloKey:
    Type: AWS::KMS::Key
    Properties:
      Description: CMK KMS Key for Apollo
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Id: key-consolepolicy
        Version: '2012-10-17'
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: 
            - Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:root'
          Action: kms:*
          Resource: "*"
        - Sid: Allow access for Key Administrators
          Effect: Allow
          Principal:
            AWS: "*"
          Action: 
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:TagResource
          - kms:UntagResource
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: "*"
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: 
              - Fn::ImportValue: Role-CumRoleLambdaAccess
              - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/apollo-glue-role"
              # - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/service-role/KinesisFirehoseServiceRole-RetinaAnal-eu-central-1-1643975004767"
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          Resource: "*"
        - Sid: Allow attachment of persistent resources
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - kms:CreateGrant
          - kms:ListGrants
          - kms:RevokeGrant
          Resource: "*"
          Condition:
            Bool:
              kms:GrantIsForAWSResource: 'true'


  ApolloKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/Apollo-CMK-key
      TargetKeyId:
        Ref: ApolloKey
    DependsOn:
      - ApolloKey


  SSMKMSKeySSEArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref SSMKMSKeySSEArnName
      Description: "SSM Parameter for KMS Key ARN"
      Type: "String"
      Value: !GetAtt [ApolloKey,Arn] 
    DependsOn: 
      - ApolloKey


  SSMKMSKeyDataArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref SSMKMSKeyDataArnName
      Description: "SSM Parameter for KMS Key ARN"
      Type: "String"
      Value: !GetAtt [ApolloKey,Arn] 
    DependsOn: 
      - ApolloKey


Outputs:

  ApolloKeyOutput:
    Description: ARN of Cum MSK Key
    Value: !GetAtt [ApolloKey, Arn] 
    Export:
      Name: !Sub KMS-Apollo-CMK-key

