# Input Parameters
#   UserArn
#   SSMKMSKeyArnNameElasticsearch
#
# Import
#   Role-CumRoleELKAccess
#
# Export
#   KMS-CumKmsKeyElasticsearch

AWSTemplateFormatVersion: '2010-09-09'
Description: Cum KMS Keys for Elasticsearch
Parameters:
  UserArn:
    Type: String
    # Default: arn:aws:iam::661623416131:user/CumulusDev-AWScli-ProgAccess

  # Parameters for SSM
  SSMKMSKeyArnNameElasticsearch:
    Type: String
    # Default: "elasticsearch.kms.arn"

Resources:
  CumKmsKeyElasticsearch:
    # DeletionPolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      Description: Cum KMS Key- Elasticsearch
      Enabled: true      
      EnableKeyRotation: true
      KeyPolicy:
        Id: key-consolepolicy
        Version: '2012-10-17'
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Ref UserArn
          Action: kms:*
          Resource: "*"
        - Sid: Allow access for Key Administrators
          Effect: Allow
          Principal:
            AWS: 
              - Fn::ImportValue: Role-CumRoleELKAccess
              - Fn::ImportValue: Role-CumRoleLambdaAccess
              - Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/LZ-SecurityAuditor'
              - Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/LZ-CloudAdmin'
          Action: kms:*
          Resource: "*"
        - Sid: Allow access for Dome9 Permissions
          Effect: Allow
          Principal:
            AWS: 
              - Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/LZ-Dome9-ReadOnly'
          Action: 
          - kms:DescribeKey
          - kms:ListKeyPolicies
          - kms:ListResourceTags
          Resource: "*"
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: 
              - Fn::ImportValue: Role-CumRoleELKAccess
              - Fn::ImportValue: Role-CumRoleLambdaAccess
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          - kms:ListKeyPolicies
          - kms:ListResourceTags
          - elasticsearch:ListTags
          Resource: "*"
        - Sid: Allow attachment of persistent resources
          Effect: Allow
          Principal:
            AWS: 
              - Fn::ImportValue: Role-CumRoleELKAccess
              - Fn::ImportValue: Role-CumRoleLambdaAccess
          Action:
          - kms:CreateGrant
          - kms:ListGrants
          - kms:RevokeGrant
          Resource: "*"
          Condition:
            Bool:
              kms:GrantIsForAWSResource: 'true'

  CumKmsKeyAliasElasticsearch:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/Cum-kms-key-Elasticsearch
      TargetKeyId:
        Ref: CumKmsKeyElasticsearch       
    DependsOn:
      - CumKmsKeyElasticsearch

  SSMKMSKeyArnElasticsearch:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref SSMKMSKeyArnNameElasticsearch
      Description: "SSM Parameter for Elasticsearch KMS Key ARN"
      Type: "String"
      Value: !GetAtt [CumKmsKeyElasticsearch,Arn] 
    DependsOn: 
      - CumKmsKeyElasticsearch

Outputs:
  CumKmsKeyOutputElasticsearch:
    Description: ARN of Cum Elasticsearch KMS Key   
    Value: !GetAtt [CumKmsKeyElasticsearch, Arn] 
    Export:
      Name: !Sub KMS-CumKmsKeyElasticsearch
