AWSTemplateFormatVersion: '2010-09-09'
Description: IAM policy and Role for kinesis firehose.
# Parameters:
#   AWSRegion:
#     Type: String
#   PrivateDnsEnabled:
#     Type: String
#   VpcId:
#     Type: String
#   SubnetIds:
#     Type: String

Resources:

  CloudWatchAccessOnly:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CloudWatchAccessOnly
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"


Outputs:
  CumMSKRole:
    # Description: The ARN of Cumulus Role for MSK
    Value: !GetAtt [CloudWatchAccessOnly,Arn]
    Export:
      Name: !Sub "Role-CloudWatchAccessOnly"
