AWSTemplateFormatVersion: '2010-09-09'
Description: Cum Roles and policies for Glue job.
Parameters:
  BucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: bucket_datalake_local
  VpcId:
    Type: String
  AWSRegion:
    Type: String
  PrivateDnsEnabled:
    Type: String
  VpcId:
    Type: String
  SubnetIds:
    Type: String
Resources:
  CumGlueServicePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Path: "/"
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: VisualEditor0
          Effect: Allow
          Action:
            - s3:*
          Resource:
            - Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - Ref: BucketName
                - "/*"
            - Fn::Join:
              - ""
              - - "arn:aws:glue:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":table/remotedl/*"
      Roles:
        - Ref: CumGlueAccessRole
      ManagedPolicyName: CumGlueServicePolicy

  CumGlueAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Effect: Allow
          Action: sts:AssumeRole
      Path: "/"
      RoleName: CumGlueAccessRole

Outputs:
  CumRoleGlueAccess:
    Description: The ARN of Cumulus - Role - Glue
    Value: !GetAtt [CumGlueAccessRole,Arn]
    Export:
      Name: !Sub "Role-CumGlueAccessRole"
