name: Trigger S3 Bucket Creation

on:
  workflow_dispatch:
    inputs:
      S3_BUCKET_NAME:
        description: 'S3 bucket name'
        required: true
      STACK_NAME:
        description: 'Stack name'
        required: true
      AWS_REGION:
        description: 'AWS region'
        required: true
      KMS_ARN:
        description: 'Optional KMS ARN'
        required: false

jobs:
  trigger-create-s3:
    uses: ./.github/workflows/create-s3-bucket.yml
    with:
      S3_BUCKET_NAME: ${{ github.event.inputs.S3_BUCKET_NAME }}
      STACK_NAME: ${{ github.event.inputs.STACK_NAME }}
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      KMS_ARN: ${{ github.event.inputs.KMS_ARN }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
