name: trigger-delete-s3

on:
  workflow_dispatch:
    inputs:
      S3_BUCKET_NAME:
        description: 'S3 Bucket Name'
        required: true
      STACK_NAME:
        description: 'Stack Name'
        required: true
      AWS_REGION:
        description: 'AWS Region'
        required: true
      LOG_LEVEL:
        description: 'Log level (default INFO)'
        required: false
        default: 'INFO'

jobs:
  call-delete-s3:
    uses: ./.github/workflows/delete-s3-bucket.yml
    with:
      S3_BUCKET_NAME: ${{ github.event.inputs.S3_BUCKET_NAME }}
      STACK_NAME: ${{ github.event.inputs.STACK_NAME }}
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      LOG_LEVEL: ${{ github.event.inputs.LOG_LEVEL }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
